"""baseline

Revision ID: 46896b176eb3
Revises: 
Create Date: 2026-05-28 15:11:13.333376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46896b176eb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_details',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classifications', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_history_event_idx', 'job_history', ['event', 'observed_at'], unique=False)
    op.create_index('job_history_job_id_idx', 'job_history', ['job_id', 'observed_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teaser', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('advertiser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subclassification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_arrangement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('bullet_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index('job_history_job_id_idx', table_name='job_history')
    op.drop_index('job_history_event_idx', table_name='job_history')
    op.drop_table('job_history')
    op.drop_table('job_details')
    # ### end Alembic commands ###
