"""baseline

Revision ID: faf8a114f4d0
Revises: 
Create Date: 2026-05-28 14:56:52.642839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faf8a114f4d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_details',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('classifications', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.Text(), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_history_event_idx', 'job_history', ['event', 'observed_at'], unique=False)
    op.create_index('job_history_job_id_idx', 'job_history', ['job_id', 'observed_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('teaser', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('advertiser_id', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('subclassification', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('work_arrangement', sa.Text(), nullable=True),
    sa.Column('salary_label', sa.Text(), nullable=True),
    sa.Column('listing_date', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Text(), nullable=True),
    sa.Column('display_type', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('bullet_points', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.Text(), nullable=True),
    sa.Column('html_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('content_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index('job_history_job_id_idx', table_name='job_history')
    op.drop_index('job_history_event_idx', table_name='job_history')
    op.drop_table('job_history')
    op.drop_table('job_details')
    # ### end Alembic commands ###
